export const FETCH_PRODUCT_CATEGORIES_DATA = "FETCH_PRODUCT_CATEGORIES_DATA";
export const FETCH_PRODUCT_CATEGORIES_SUCCESS =
	"FETCH_PRODUCT_CATEGORIES_SUCCESS";
export const FETCH_PRODUCT_CATEGORIES_FAIL = "FETCH_PRODUCT_CATEGORIES_FAIL";
