export const FETCH_SLIDES_DATA = "FETCH_SLIDES_DATA";
export const FETCH_SLIDES_SUCCESS = "FETCH_SLIDES_SUCCESS";
export const FETCH_SLIDES_FAIL = "FETCH_SLIDES_FAIL";

export const FETCH_CATEGORIES_DATA = "FETCH_CATEGORIES_DATA";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
export const FETCH_CATEGORIES_FAIL = "FETCH_CATEGORIES_FAIL";

export const FETCH_LATEST_PRODUCTS_DATA = "FETCH_LATEST_PRODUCTS_DATA";
export const FETCH_LATEST_PRODUCTS_SUCCESS = "FETCH_LATEST_PRODUCTS_SUCCESS";
export const FETCH_LATEST_PRODUCTS_FAIL = "FETCH_LATEST_PRODUCTS_FAIL";

export const FETCH_SALESADS_DATA = "FETCH_SALESADS_DATA";
export const FETCH_SALESADS_SUCCESS = "FETCH_SALESADS_SUCCESS";
export const FETCH_SALESADS_FAIL = "FETCH_SALESADS_FAIL";

export const FETCH_POPULAR_SERVICES_DATA = "FETCH_POPULAR_SERVICES_DATA";
export const FETCH_POPULAR_SERVICES_SUCCESS = "FETCH_POPULAR_SERVICES_SUCCESS";
export const FETCH_POPULAR_SERVICES_FAIL = "FETCH_POPULAR_SERVICES_FAIL";

export const FETCH_LATEST_NEWS_DATA = "FETCH_LATEST_NEWS_DATA";
export const FETCH_LATEST_NEWS_SUCCESS = "FETCH_LATEST_NEWS_SUCCESS";
export const FETCH_LATEST_NEWS_FAIL = "FETCH_LATEST_NEWS_FAIL";

export const FETCH_COMMENTS_DATA = "FETCH_COMMENTS_DATA";
export const FETCH_COMMENTS_SUCCESS = "FETCH_COMMENTS_SUCCESS";
export const FETCH_COMMENTS_FAIL = "FETCH_COMMENTS_FAIL";
