export const GET_ALL_USERS_DATA = "GET_ALL_USERS_DATA";
export const GET_ALL_USERS_DATA_SUCCESS = "GET_ALL_USERS_DATA_SUCESS";
export const GET_ALL_USERS_DATA_FAIL = "GET_ALL_USERS_DATA_FAIL";

export const GET_USER_DATA = "GET_USER_DATA";
export const GET_USER_DATA_SUCCESS = "GET_USER_DATA_SUCESS";
export const GET_USER_DATA_FAIL = "GET_USER_DATA_FAIL";

export const GET_ALL_ORDER_DATA = "GET_ALL_ORDER_DATA";
export const GET_ALL_ORDER_DATA_SUCCESS = "GET_ALL_ORDER_DATA_SUCESS";
export const GET_ALL_ORDER_DATA_FAIL = "GET_ALL_ORDER_DATA_FAIL";

export const GET_ORDER_DATA = "GET_ORDER_DATA";
export const GET_ORDER_DATA_SUCCESS = "GET_ORDER_DATA_SUCESS";
export const GET_ORDER_DATA_FAIL = "GET_ORDER_DATA_FAIL";

export const GET_ALL_REVIEWS_DATA = "GET_ALL_REVIEWS_DATA";
export const GET_ALL_REVIEWS_DATA_SUCCESS = "GET_ALL_REVIEWS_DATA_SUCCESS";
export const GET_ALL_REVIEWS_DATA_FAIL = "GET_ALL_REVIEWS_DATA_FAIL";

export const GET_REVIEW_DATA = "GET_AREVIEWS_DATA";
export const GET_REVIEW_DATA_SUCCESS = "GET_REVIEW_DATA_SUCCESS";
export const GET_REVIEW_DATA_FAIL = "GET_REVIEW_DATA_FAIL";
