export const FETCH_MENU_SUCCESS = "FETCH_MENU_SUCCESS";
export const FETCH_MENU_FAIL = "FETCH_MENU_FAIL";
export const FETCH_MENU_DATA = "FETCH_MENU_DATA";

export const FETCH_LOGO_DATA = "FETCH_LOGO_DATA";
export const FETCH_LOGO_SUCCESS = "FETCH_LOGO_SUCCESS";
export const FETCH_LOGO_FAIL = "FETCH_LOGO_FAIL";

export const FETCH_SLIDES_DATA = "FETCH_SLIDES_DATA";
export const FETCH_SLIDES_SUCCESS = "FETCH_SLIDES_SUCCESS";
export const FETCH_SLIDES_FAIL = "FETCH_SLIDES_FAIL";

export const FETCH_CATEGORIES_DATA = "FETCH_CATEGORIES_DATA";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
export const FETCH_CATEGORIES_FAIL = "FETCH_CATEGORIES_FAIL";
