export const FETCH_MENU_SUCCESS = "FETCH_MENU_SUCCESS";
export const FETCH_MENU_FAIL = "FETCH_MENU_FAIL";
export const FETCH_MENU_DATA = "FETCH_MENU_DATA";

export const FETCH_LOGO_DATA = "FETCH_LOGO_DATA";
export const FETCH_LOGO_SUCCESS = "FETCH_LOGO_SUCCESS";
export const FETCH_LOGO_FAIL = "FETCH_LOGO_FAIL";

export const FETCH_SITE_DATA = "FETCH_SITE_DATA";
export const FETCH_SITE_SUCCESS = "FETCH_SITE_SUCCESS";
export const FETCH_SITE_FAIL = "FETCH_SITE_FAIL";

export const FETCH_ALL_PRODUCTS_DATA = "FETCH_ALL_PRODUCTS_DATA";
export const FETCH_ALL_PRODUCTS_SUCCESS = "FETCH_ALL_PRODUCTS_SUCCESS";
export const FETCH_ALL_PRODUCTS_FAIL = "FETCH_ALL_PRODUCTS_FAIL";
